# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  copyq-darwin = {
    pname = "copyq-darwin";
    version = "7.1.0";
    src = fetchurl {
      url = "https://github.com/hluk/CopyQ/releases/download/v7.1.0/CopyQ.dmg.zip";
      sha256 = "sha256-8dYfEZSSI5NHGXXA+KzPg61Y7Z6nezo0Knced3j3TRU=";
    };
  };
  qutebrowser-darwin = {
    pname = "qutebrowser-darwin";
    version = "3.1.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.1.0/qutebrowser-3.1.0.dmg";
      sha256 = "sha256-AvuuwUnxMcr2ekZ/O1FL/4IizV1aTMhXNrbf1SwNY7U=";
    };
  };
  vivaldi-darwin = {
    pname = "vivaldi-darwin";
    version = "6.5.3206.53";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.6.5.3206.53.universal.dmg";
      sha256 = "sha256-+nUcO4jp0l6JfKFQvsCm+WruldUAJGuw9nvm+W1z+nE=";
    };
  };
}
